### ISSUE TITLE
Error: Cannot find module './is'

### ISSUE THREAD

**Issue by shotlom** [KoryNunn/fastn#19]
Hi, I tried just the bare minimum example from the readme.md and got a module error. 

I installed with ```npm i fastn --save```, and then browserified the following:

```javascript
// Require and initialise fastn
var fastn = require('fastn/')({
    // component constructors
    _generic: require('fastn/genericComponent'),
    list: require('fastn/listComponent')
});

var something = fastn('h1', 'Hello World');

document.body.appendChild(something.element);
``` 

The full error message is: 

```
Error: Cannot find module './is' from '/home/adminuser/Dev/fastn-test'
    at /home/adminuser/Dev/fastn-test/node_modules/browserify/node_modules/resolve/lib/async.js:55:21
    at load (/home/adminuser/Dev/fastn-test/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/adminuser/Dev/fastn-test/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /home/adminuser/Dev/fastn-test/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at Object.oncomplete (fs.js:107:15)
```

**Comment by KoryNunn** [comment]
There are a few issues with the bare minimum in the README, but I'm not sure why it is complaining about ./is.js

I'll update the readme with the correct example, but also investigate the error.

**Comment by KoryNunn** [comment]
The README has been updated.

**Comment by KoryNunn** [comment]
I also tried creating a fresh folder, installing fastn, and browserifing the above code, which succeeded.

When attempting to run the code, I got the expected error, `Uncaught TypeError: Cannot read property 'appendChild' of null`, because the component hadn't been rendered.

How did you browserify your project?

**Comment by shotlom** [comment]
```browserify app.js -p index.brower.js```

**Comment by KoryNunn** [comment]
The usual command for browserification is:
```
browserify input.js > output.js
```

can you please try the updated code and let me know if there are still issues?

**Comment by shotlom** [comment]
Why why why no work.

[Test repo](https://github.com/shotlom/fatsn-test)

I'm now running with [beefy](https://www.npmjs.com/package/beefy)

**Comment by KoryNunn** [comment]
Works in my branch after adding an onload handler.

You can't add an element to `document.body` before `document.body` exists.

**Comment by KoryNunn** [comment]
PR open here fyi: https://github.com/shotlom/fatsn-test/pull/1/files

**Comment by shotlom** [comment]
Got it - that's fixed it, and the basic README.md example now works out of the box.

Cheers,
