### ISSUE TITLE
just a friendly question about classes, ids, and attributes

### ISSUE THREAD

**Issue by BenjaminVerble** [KoryNunn/fastn#37]
I'm just taking a first look at fastn and am finding it interesting. what is the "fastn way" (not that there has to be one) of adding attributes or classes to an element? Would I create an element with fastn and then use the normal dom methods: element.classlist.add('foo') ? Or is there a more fancy fastn way?

**Comment by KoryNunn** [comment]
Whoops misclicked on my phone..

Check out the example app source, any component that is handled by `genericComponent.js` ( which is almost every component in the example ) adds attributes and properties via the settings object passed as the second parameter, eg.

```
fastn('div', {class:'someClass'})
```

**Comment by KoryNunn** [comment]
As for id's, there is practically no reason to add an I'd to any element other than if another library needs a DOM node with an ID on it for some reason. fastn has no need for id's.

**Comment by KoryNunn** [comment]
Unless you are asking about calculated classes, like say, a .user that has a .selected when they are selected, in which case:

```
fastn('div', {
    class: fastn.binding('selected', function(selected){
        return ['user', selected ? 'selected' : ''];
    })
})
```

is one approach.

**Comment by BenjaminVerble** [comment]
Thank you for your detailed explanations. The only reason why I have used IDs in the past is that understood document.getElementByID to be faster than document.querySelector, but your point about fastn not needing ids makes sense. I do also find your calculated class pattern helpful. If I become invested in fastn, I'll contribute a PR for documentation or examples. Thanks again for your response.

**Comment by KoryNunn** [comment]
You don't need to do any DOM queries within fastn components as each component has a reference to its element. This is one of the things that makes it so fast.

The performance difference between getElementByID() and querySelectorAll() these days is negligible or non-existent, so even ignoring  fastn, that isn't a reason to use IDs any more.
