### ISSUE TITLE
typeahead dropdown autocomplete example

### ISSUE THREAD

**Issue by shotlom** [KoryNunn/fastn#40]
I'm looking for this type of functionality in a fairly basic form which has 3 fields (of course Password won't have typeahead however).

Usual suspects - list of companies, list of users, hidden password as the user types, so that each character is a "*".

* company
* user
* password

https://twitter.github.io/typeahead.js/examples/

**Comment by KoryNunn** [comment]
password masking is native to web.

You can achieve this by setting an inputs type to 'password'

http://korynunn.github.io/fastn/try/#InZhciBhcHAgPSBmYXN0bignaW5wdXQnLCB7XG4gIFx0XHR0eXBlOidwYXNzd29yZCdcblx0fSlcblxucmV0dXJuIGFwcDsi

**Comment by shotlom** [comment]
Yep got it.

On Wed, Jul 8, 2015 at 1:02 PM, Kory Nunn <notifications@github.com> wrote:

> password masking is native to web.
>
> You can achieve this by setting an inputs type to 'password'
>
>
> http://korynunn.github.io/fastn/try/#InZhciBhcHAgPSBmYXN0bignaW5wdXQnLCB7XG4gIFx0XHR0eXBlOidwYXNzd29yZCdcblx0fSlcblxucmV0dXJuIGFwcDsi
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KoryNunn/fastn/issues/40#issuecomment-119406785>.
>



-- 
Mr Sholto Maud

mobile: +61 (0) 424 094 227
email: sholto.maud@gmail.com
skype: sholtomaud
