### ISSUE TITLE
not working with cordova & Android <4.4

### ISSUE THREAD

**Issue by shotlom** [KoryNunn/fastn#41]
The repo below is a basic fastn app to be built with cordova, it contains code that both works and doesn't work.

Fastn appears to fail for version 4.1.2 of Android, I haven't been able to debug sufficiently as the remote debugging tools don't appear to work for Android  below 4.4

```javascript
var working = fastn('div',
	fastn('div','Some Company'), 
	fastn('h2','Some other Company')
);

var notWorking = fastn('div',
	fastn('div',{'class':'company'},'Some Company'), 
	fastn('h2','Some other Company')
);

```

https://github.com/shotlom/fatsn-test-cordova

**Comment by shotlom** [comment]
This is fixed with the cordova-crosswalk plugin, but it slows down the run step when installing an app to a device.
https://github.com/shotlom/fatsn-test-cordova gives a working example

**Comment by KoryNunn** [comment]
Could you try running the not working code again on 4.1.2 without corsswalk, but with this as the first code that runs:

```

window.onerror = function(error){
    alert(error.message);
}

```

**Comment by shotlom** [comment]
I just get a white screen, which is the same as what I get without crosswalk but with `{'class':'someclass'}`

**Comment by KoryNunn** [comment]
is the window.onerror code the absolute first code that runs? if so, no error is being thrown, so I don't know what to do.

**Comment by shotlom** [comment]
Yep, that was the ONLY code being run.

I don't know either, so the workaround is to use the cordova-crosswalk
plugin which both works fine,  AND gives debugging over USB so it's a
tradeoff.


On Wed, Aug 5, 2015 at 4:48 PM, Kory Nunn <notifications@github.com> wrote:

> is the window.onerror code the absolute first code that runs? if so, no
> error is being thrown, so I don't know what to do.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KoryNunn/fastn/issues/41#issuecomment-127892442>.
>



-- 
Mr Sholto Maud

mobile: +61 (0) 424 094 227
email: sholto.maud@gmail.com
skype: sholtomaud

**Comment by KoryNunn** [comment]
Yeah that's weird, and seems unrelated to fastn.

One downside to crosswalk is that it increased the size of the app by about 30MB, since it effectively bundles an entire browser with it.

**Comment by shotlom** [comment]
Well I wouldn't say it was unrelated to fastn, this is all about fastn! :)

I believe the design intent for fastn was to support hybrid mobile apps
with cordova/phonegap (any other technologies?).

Can I suggest you mention in the doco that to build hybrid mobile apps with
fastn + cordova you also need crosswalk for older browsers (i.e. Android OS
v4.1.2).






On Wed, Aug 5, 2015 at 5:10 PM, Kory Nunn <notifications@github.com> wrote:

> Yeah that's weird, and seems unrelated to fastn.
>
> One downside to crosswalk is that it increased the size of the app by
> about 30MB, since it effectively bundles an entire browser with it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KoryNunn/fastn/issues/41#issuecomment-127896885>.
>



-- 
Mr Sholto Maud

mobile: +61 (0) 424 094 227
email: sholto.maud@gmail.com
skype: sholtomaud

**Comment by KoryNunn** [comment]
There is no reason that I can see that fastn shouldn't work on old android browser. I'll see if I can find an old phone to test it out on.
