### ISSUE TITLE
Activities example 

### ISSUE THREAD

**Issue by shotlom** [KoryNunn/fastn#49]
http://korynunn.github.io/fastn/activities/

1. Open x3 activities (0,1,2)
2. Use browser navigation to navigate backwards
3. Activities go back and forth between activity 1 & 2 only

Is this the desired function?

I would have thought you would navigate all the way back to activity 0?

**Comment by KoryNunn** [comment]
That's odd, will investigate. Might be an issue with https://github.com/KoryNunn/activity-router

**Comment by shotlom** [comment]
Any update?

**Comment by KoryNunn** [comment]
Resolved via: https://github.com/KoryNunn/activity-router/commit/bd24ab126a088a6495ab68abacbf1994dc253fd7

**Comment by shotlom** [comment]
:+1:
